# Generated by Django 2.1.7 on 2019-03-13 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('major_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='전공ID')),
                ('major_title', models.CharField(max_length=100, verbose_name='전공명')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentID', models.IntegerField(primary_key=True, serialize=False, verbose_name='학생ID')),
                ('name', models.CharField(max_length=20, verbose_name='이름')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='전화번호')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='주소')),
                ('hobby', models.CharField(blank=True, max_length=50, null=True, verbose_name='취미')),
                ('skill', models.CharField(blank=True, max_length=50, verbose_name='기술')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Major', verbose_name='전공ID')),
            ],
        ),
    ]