# Generated by Django 2.1.7 on 2019-03-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentID', models.IntegerField(verbose_name='학생ID')),
                ('name', models.CharField(max_length=20, verbose_name='이름')),
                ('major_id', models.IntegerField(verbose_name='전공ID')),
                ('phone', models.CharField(max_length=20, verbose_name='전화번호')),
                ('address', models.CharField(max_length=100, verbose_name='주소')),
                ('hobby', models.CharField(max_length=50, verbose_name='취미')),
                ('skill', models.CharField(max_length=50, verbose_name='기술')),
            ],
        ),
        migrations.AlterField(
            model_name='major',
            name='major_id',
            field=models.IntegerField(verbose_name='전공ID'),
        ),
    ]
