# Generated by Django 2.1.7 on 2019-03-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20190312_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='student',
            name='hobby',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='취미'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='전화번호'),
        ),
    ]
