# Generated by Django 2.1.7 on 2019-03-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20190312_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='skill',
            field=models.CharField(blank=True, max_length=50, verbose_name='기술'),
        ),
    ]
